In [15]:
import torch
size = 6
a = [[i-1, i] for i in range(size-1)]
a.append([0, -1])
a = torch.tensor(a) # 10, 2
# b = torch.tensor([[i + 5, i + 6] for i in range(10)]) # 10, 2
print(a.shape)
print(a)
# print(b)

view2 = torch.repeat_interleave(a[:, 0], size)
view1 = a[:, 1].repeat(size)
print(view1)
print(view2)
view = torch.bitwise_or(torch.bitwise_and((view1 == view2 ).reshape((size, -1)), a[:, 0] != -1), \
                    torch.bitwise_and((view1 == view2 ).reshape((size, -1)), a[:, 1] != -1))

view = view + view.T
print(view)

torch.Size([6, 2])
tensor([[-1,  0],
        [ 0,  1],
        [ 1,  2],
        [ 2,  3],
        [ 3,  4],
        [ 0, -1]])
tensor([ 0,  1,  2,  3,  4, -1,  0,  1,  2,  3,  4, -1,  0,  1,  2,  3,  4, -1,
         0,  1,  2,  3,  4, -1,  0,  1,  2,  3,  4, -1,  0,  1,  2,  3,  4, -1])
tensor([-1, -1, -1, -1, -1, -1,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,
         2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  0,  0,  0,  0,  0,  0])
tensor([[False,  True, False, False, False,  True],
        [ True, False,  True, False, False, False],
        [False,  True, False,  True, False, False],
        [False, False,  True, False,  True, False],
        [False, False, False,  True, False, False],
        [ True, False, False, False, False, False]])


In [24]:
import torch
import numpy as np

B = 6
a = torch.tensor([[i, i+1] for i in range(B)]) # 8, 2
dist = a.unsqueeze(0) - a.unsqueeze(1)
print(dist.shape)
print(a)
# print(np.linalg.norm(np.array(dist), ord=2, axis=-1))
print(torch.sqrt(torch.sum(dist*dist, dim=-1)))
dist_loss = torch.mean(torch.sqrt(torch.sum(dist*dist, dim=-1)) * view)

print(dist_loss)

torch.Size([6, 6, 2])
tensor([[0, 1],
        [1, 2],
        [2, 3],
        [3, 4],
        [4, 5],
        [5, 6]])
tensor([[0.0000, 1.4142, 2.8284, 4.2426, 5.6569, 7.0711],
        [1.4142, 0.0000, 1.4142, 2.8284, 4.2426, 5.6569],
        [2.8284, 1.4142, 0.0000, 1.4142, 2.8284, 4.2426],
        [4.2426, 2.8284, 1.4142, 0.0000, 1.4142, 2.8284],
        [5.6569, 4.2426, 2.8284, 1.4142, 0.0000, 1.4142],
        [7.0711, 5.6569, 4.2426, 2.8284, 1.4142, 0.0000]])
tensor(0.7071)
